language: java
jdk:
- openjdk8
services:
- postgresql
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_script:
- psql --command="CREATE USER dev"
- psql --command="CREATE DATABASE monzun_testing WITH OWNER = dev";
script: "./mvnw clean install"
env:
  global:
  - secure: KmzQj6TwSJZs/ny1WIhMxl8sFUZHRla7CX+IN6A0ukjoa05fUT6wSotDjQWm7XRMtngMO5nB0WDzyo18NC6hAK5sSa7hMkoZOAvfEgDDN/PAnEoKitxd7KRb7dqv6g28Ln/y6x9hznaZBDGlntVZpO0AbtgVOj+IpqC5fcDnM6mwM46pnvW9PL2zryGsbGLnys0YVCRFpyzagYqIAjS/1cNawtc0lsLaRRj0RbSe0T4+9UDuGY6owspJ0p8MXXSvutsr2m3DbGdoFqC8N9ItpcHlhpWmgPhfWEd+zuhce5Pb8kf1RgOPoZZ9ZyPqG2qqOjiceCdQNPfqwDFKi4irSW8U80UL37qodDHTmBpuJ/c68KkmSyOVbxdwfqf9YrJHLBjbu1V+h1CKuluWaI95mXNdfysd/cpKkPxFsnvlEIKcf3ArSfNf4mwfhvsccCn7foEd76MmFdXLGfZcJ0MrHr1+YQuaJNuWwfCFQa4Pp5AHBviqN0AZzGYuiH3fL6djODj2vml1DwnKlXwCqYodifj/HC2tC92HnwmQMTOD9GNnesobqMl+dbl/xGeQ4jHpMnyD077o6TGQr5PZJMYZJLY6UyColOwYvqtv47Y98yu67EWRAzFFdiIF4LN4pLKe2FkD06I9jspwUBiy+UVpVzZRZ/ly2bpOXPcgVQ1fiXo=
  - secure: N4EpcKtP4SDlAD0WE3TgV8fXcQZ6FgBEGsHlG0SCYeOvy6Upbrbfhzrhn3q2B0xmsCpnVswJOPKV3VkYdejuKdm96vNfV+5t50GRDXi5UydOliP3hmkWYg3cIrYHxYy6DSMYMUS2vo8DEi1az/N8y8qHVpujM5G+atPhMMVrUem6kO2YwxHMdeP8MrUBW3+bgGjTULVZiPCKyo6fyqYMxF/x4Ott1YqU0WpcmsudCm5YvncbY3d2TP/nK7HlOzUTyy2e5lUJR9pc/K2lSa4+E3XemlpFtcdoiR4S+D1TDjyAbSp+MnKYVseMlaSvR0Sqa2rqcyBBRcEOmB4S9amG4NI8HmHoFFtcYOBJiHN92TAlnVq0n6R+0XYGnyeWQ7td+a0X0wYWePUXZv1LXTXPcxIGggQLkz4FWLurOn1BjA60WnxkFqEISCYBb+aXKhOM4VXULza1XfEXxSkwBIuyZw2rP6k6wSYxOzbJlipddDm5upBLtifsbrigfhztiWGKCjO/7XbN2B2+PynwktPD9mbpRZVJzyZwu+7ZwgpHAnNrz9p1C67Z0592ldCc2EDzkAEftPDQAsuQ12Lnqq8Ka77K3pJZM858u7KZdXtF3R8UOImMUjwKQ2OjySbq3tetmbLZNU+3YprEAnfxA+fcVNOq71ShgSKetPRRfNIHGS8=
