language: java
jdk:
  - openjdk8
script: ./mvnw clean install
services:
  - postgresql

addons:
  postgresql: '9.6'
before_script:
  - psql --command="CREATE USER dev"
  - psql --command="CREATE DATABASE monzun_testing WITH OWNER = dev;"