language: java
jdk:
- openjdk8
services:
- postgresql
addons:
  postgresql: '10.15'
before_script:
- psql --command="CREATE USER dev"
- psql --command="CREATE DATABASE monzun_testing WITH OWNER = dev";
script: "./mvnw clean install"
env:
  global:
  - secure: gSD7PRWq4nMvmDgBpN7HOrtwVJqN7CNEf9wpxG9JFjxU+o6OLg2n69r8jAfYxV9NS6yTVvv9grc1BZRzIo26FctnFI9To1OsOILZaoU9gqOlF5GOyO7alsuBCZ+Dm9bMPm80whfUreMNVGU4T1Erc7hlwtxO3gof27FIKQih97856Dm4r3fn5sTYLRY+z0gkHacYu5YbIXeWnSTJ0lYE6rPzY0FhgVm69wApG6Tt0u+kuTB/xfne3Xpg6GWKtPb8lomctL355X91HboI19Pf7PNP84vfPwYCIp67Q4LG5McgJRao5PP12pP0sobNKmq96Z/HC5CXQsLz6gYGm6Jo9q4XyehjzZY9e4m9T/w/TO3s65Lxh7LYGLv7muADfkuS0uWJPiULbuNpsSP6Co9N4PY03N4udd5ik0ta4grvL1wAQkUcerJ6mzn8L/YYkrpf/5QTLObJJOubeVExQKkWdG1Ezmi+QGc4xIdkz/GHZ6vJof0uQNdEN0kt84nt5ii0afzlEXcL4/Z0g+8i8NR7a8whB7QqgP7Z8cE6BVYWfNXUMibIPE4aCFgH50YEOUaMBnWx+tlkNVE8MjL1PJUH0X3saoqDMmUwo0fIP4Qu3uADdCkyku/yM8uDVVostNwO3EQMXZRLrN8DQo3Vi7oPbk+EaI+GOgMs/kGe87Ci/tg=
  - secure: KmzQj6TwSJZs/ny1WIhMxl8sFUZHRla7CX+IN6A0ukjoa05fUT6wSotDjQWm7XRMtngMO5nB0WDzyo18NC6hAK5sSa7hMkoZOAvfEgDDN/PAnEoKitxd7KRb7dqv6g28Ln/y6x9hznaZBDGlntVZpO0AbtgVOj+IpqC5fcDnM6mwM46pnvW9PL2zryGsbGLnys0YVCRFpyzagYqIAjS/1cNawtc0lsLaRRj0RbSe0T4+9UDuGY6owspJ0p8MXXSvutsr2m3DbGdoFqC8N9ItpcHlhpWmgPhfWEd+zuhce5Pb8kf1RgOPoZZ9ZyPqG2qqOjiceCdQNPfqwDFKi4irSW8U80UL37qodDHTmBpuJ/c68KkmSyOVbxdwfqf9YrJHLBjbu1V+h1CKuluWaI95mXNdfysd/cpKkPxFsnvlEIKcf3ArSfNf4mwfhvsccCn7foEd76MmFdXLGfZcJ0MrHr1+YQuaJNuWwfCFQa4Pp5AHBviqN0AZzGYuiH3fL6djODj2vml1DwnKlXwCqYodifj/HC2tC92HnwmQMTOD9GNnesobqMl+dbl/xGeQ4jHpMnyD077o6TGQr5PZJMYZJLY6UyColOwYvqtv47Y98yu67EWRAzFFdiIF4LN4pLKe2FkD06I9jspwUBiy+UVpVzZRZ/ly2bpOXPcgVQ1fiXo=
